title: Github Page for Scooter Norton
description: This is my personal website hosted on GitHub Pages.
baseurl: ""
url: "https://scootern917.github.io/github"
theme: minima


author:
  name: "Scooter Norton"
  email: "scootern917@gmail.com"
  social:
    github: https://github.com/scootern917
